In [20]:
# Numpy is a great library to work with multidimensional array objects
import numpy as np

np_space = np.array([1,10,2,3,14,1])
np_time = np.array([1,2,3,4,5,6])
np_velocity = np_space/np_time
print(np_velocity)

[1.         5.         0.66666667 0.75       2.8        0.16666667]


In [21]:
# Modifying vector 
np_velocity = np_velocity * 2
print(np_velocity)

[ 2.         10.          1.33333333  1.5         5.6         0.33333333]


In [22]:
# Selecting a specific value by index (zero based)
print(np_velocity[2])

1.3333333333333333


In [23]:
# Extract a subarray
np_subVelocity = np_velocity[1:3]
print(np_subVelocity)

[10.          1.33333333]


In [5]:
# Creating vectors
import numpy as np

n = np.arange(25)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
# Converting to matrix
n.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [2]:
# Creating vectors by steps
import numpy as np

#Call only even numbers
n = np.arange(0,25,2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [30]:
# Unsing zeros function
import numpy as np

n = np.zeros(6)
n

array([0., 0., 0., 0., 0., 0.])

In [7]:
# Using ones function
m = np.ones(8)
m

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
# Using linspace function
import numpy as np

# 20 values between 0 and 5 
n = np.linspace(0, 5, 20)
n

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [10]:
# Generating uniform distribution [0 to 1]
np.random.rand(10)

array([0.92911036, 0.06643476, 0.31671169, 0.89736398, 0.46901799,
       0.55060339, 0.82251168, 0.47347793, 0.83337876, 0.93602045])

In [14]:
# Generating a standard normal distribution [-1 to 1]
np.random.randn(10)

array([-0.84968789,  1.30735213, -0.53765494, -0.58731811, -0.22916664,
        0.52240426, -0.07036874,  1.17610838, -1.35898186,  0.76095778])

In [15]:
# Generating a random integer between 1 and 100
np.random.randint(1, 100)

49

In [17]:
# Generating an array of integers between 1 and 100
np.random.randint(1, 100, 10)

array([28,  7,  9, 26, 52, 65, 90,  5, 25, 37])

In [26]:
# Methods for arrays
import numpy as np
arr = np.random.randint(0, 50, 25)
arr

array([ 2, 49, 22, 20, 48, 47,  0, 43, 20, 22, 36, 21, 26, 18,  7, 13,  7,
       37, 38, 12, 26, 20, 44, 35, 25])

In [27]:
# Max value in array
arr.max()

49

In [28]:
# Index of max value
arr.argmax()

1

In [29]:
# Min value in array
arr.min()

0

In [34]:
# Indexing and selecting
import numpy as np

vect = np.arange(0,20)
vect

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [36]:
# Selecting sub-array. It does not include the second value.
vect[1:8]

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
# Selecting array from one position to the end
vect[3:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
# Filling several postions with same value
vect[0:4] = 50
vect

array([50, 50, 50, 50,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [44]:
# Numpy arrays does not create copies by default
import numpy as np

vect = np.arange(0,20)
part = vect[0:5]
part[:] = 100

#vect is affected
vect


array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19])

In [45]:
# For creates copies use:
import numpy as np

vect = np.arange(0,20)
part = vect[0:5].copy()
part[:] = 100

#vect is not affected
vect

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [47]:
# Conditional selecting
import numpy as np

vect = np.arange(0,20)
vect[vect % 2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])