In [20]:
# Numpy is a great library to work with multidimensional array objects
import numpy as np

np_space = np.array([1,10,2,3,14,1])
np_time = np.array([1,2,3,4,5,6])
np_velocity = np_space/np_time
print(np_velocity)

[1.         5.         0.66666667 0.75       2.8        0.16666667]


In [21]:
# Modifying vector 
np_velocity = np_velocity * 2
print(np_velocity)

[ 2.         10.          1.33333333  1.5         5.6         0.33333333]


In [22]:
# Selecting a specific value by index (zero based)
print(np_velocity[2])

1.3333333333333333


In [23]:
# Extract a subarray
np_subVelocity = np_velocity[1:3]
print(np_subVelocity)

[10.          1.33333333]


In [5]:
# Creating vectors
import numpy as np

n = np.arange(25)
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [6]:
# Converting to matrix
n.reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])